"""Takes the joined variant table generated by the join_per_sample_variant_tables.py script and fills in homozygous-reference genotypes for loci that have no genotype for a sample but fall inside that sample's dipcall confidence regions.

Inputs:
- joined variant table
- dipcall confidence region bed file for each sample in the joined variant table

Outputs:
- joined variant table where loci with a missing genotype for a sample are set to homozygous reference (repeat counts = NumRepeatsInReference) when the locus is inside that sample's dipcall confidence region; genotypes outside the confidence region are left missing
"""

import argparse
import collections
import gzip
from intervaltree import IntervalTree, Interval
import os
import polars as pl
import tqdm

parser = argparse.ArgumentParser(description="Fill in homozygous-reference genotypes for missing-genotype loci inside dipcall confidence regions")
parser.add_argument("--output-tsv", help="Output joined variant table as a gzipped tsv file")
parser.add_argument("joined_variant_table", help="Joined variant table")
parser.add_argument("dipcall_confidence_regions", nargs="+", help="Dipcall confidence region bed file for each sample in the joined variant table")

args = parser.parse_args()

if not os.path.exists(args.joined_variant_table):
    parser.error(f"Joined variant table file {args.joined_variant_table} does not exist")

if not args.output_tsv:
    args.output_tsv = args.joined_variant_table.replace(".tsv", ".with_hom_ref_filled_in.tsv")

# Define schema for the joined variant table
# We need to specify Chrom as Utf8 to handle X, Y, etc.
schema_overrides = {
    "Chrom": pl.Utf8,
    "Start1Based": pl.Int32,
    "End1Based": pl.Int32,
    "Locus": pl.Utf8,
    "LocusId": pl.Utf8,
    "Motif": pl.Utf8,
    "CanonicalMotif": pl.Utf8,
    "MotifSize": pl.Int32,
    "NumRepeatsInReference": pl.Float32,
    "IsFoundInReference": pl.Boolean,
}

joined_variant_table = pl.read_csv(
    args.joined_variant_table, 
    separator="\t",
    schema_overrides=schema_overrides
)

sample_ids = set()
for column in joined_variant_table.columns:
    if column.startswith("NumRepeatsShortAllele:") or column.startswith("NumRepeatsLongAllele:"):
        sample_ids.add(":".join(column.split(":")[1:]))

print(f"Found {len(sample_ids):,d} samples in {args.joined_variant_table}")

sample_ids_to_bed_file_paths = {}
for sample_id in sample_ids:
    # find the dipcall confidence region bed file for this sample
    matching_bed_file_path = None
    for bed_file_path in args.dipcall_confidence_regions:
        bed_filename = os.path.basename(bed_file_path)
        # require sample_id to be followed by "." (e.g. "HG002.dip.bed.gz") so a shorter id can't match a longer
        # one's file as a substring (e.g. "HG002" must not match "HG00254.dip.bed.gz")
        if bed_filename.startswith(f"{sample_id}."):
            if matching_bed_file_path is not None:
                parser.error(f"Multiple DipCall confidence region bed files found for sample {sample_id}: {matching_bed_file_path} and {bed_file_path}")

            matching_bed_file_path = bed_file_path
            
    if matching_bed_file_path is None:
        parser.error(f"No dipcall confidence region bed file found for sample {sample_id}")

    if not os.path.isfile(matching_bed_file_path):
        parser.error(f"Dipcall confidence region bed file {matching_bed_file_path} does not exist")

    sample_ids_to_bed_file_paths[sample_id] = matching_bed_file_path


for bed_file_i, (sample_id, bed_file_path) in tqdm.tqdm(enumerate(sample_ids_to_bed_file_paths.items()), total=len(sample_ids_to_bed_file_paths), unit=" samples"):
    print(f"Processing sample {sample_id} from {bed_file_path}")
    # read the bed file
    # Define schema for BED file - chrom should be Utf8 to handle complex chromosome names
    bed_schema_overrides = {
        "chrom": pl.Utf8,
        "start": pl.Int32,
        "end": pl.Int32,
    }
    
    dipcall_confidence_regions = pl.read_csv(
        bed_file_path, 
        separator="\t", 
        has_header=False, 
        new_columns=["Chrom", "Start0Based", "End1Based"],
        schema_overrides=bed_schema_overrides
    )
    #print(dipcall_confidence_regions)

    EMPTY_INTERVAL_TREE = IntervalTree()
    confidence_region_interval_trees = collections.defaultdict(IntervalTree)
    total_bases = 0
    for row in dipcall_confidence_regions.iter_rows(named=True):
        if "_" in row["Chrom"]:
            continue
        normalized_chrom = row["Chrom"].replace("chr", "").upper()
        confidence_region_interval_trees[normalized_chrom].add(Interval(row["Start0Based"], row["End1Based"]))
        total_bases += row["End1Based"] - row["Start0Based"]

    print(f"Total bases in {bed_file_path}: {total_bases:,d}")
    # for each row in the joined variant table, check if the locus is in the interval tree

    set_to_hom_ref = set()
    for row in joined_variant_table.iter_rows(named=True):
        # if both the short and long alleles are "missing" accourding to polars, set the genotype to homozygous reference
        if row[f"NumRepeatsShortAllele:{sample_id}"] is None and row[f"NumRepeatsLongAllele:{sample_id}"] is None:
            normalized_chrom = row["Chrom"].replace("chr", "").upper()
            if confidence_region_interval_trees.get(normalized_chrom, EMPTY_INTERVAL_TREE).overlaps(row["Start1Based"] - 1, row["End1Based"]):
                set_to_hom_ref.add(row["LocusId"])

    print(f"Resetting {len(set_to_hom_ref):,d} out of {joined_variant_table.height:,d} ({(len(set_to_hom_ref)/joined_variant_table.height):.1%}) genotypes to homozygous reference for sample {sample_id}")

    joined_variant_table = joined_variant_table.with_columns(
        pl.when(pl.col(f"LocusId").is_in(set_to_hom_ref)).then(pl.col(f"NumRepeatsInReference")).otherwise(pl.col(f"NumRepeatsShortAllele:{sample_id}")).alias(f"NumRepeatsShortAllele:{sample_id}"),
        pl.when(pl.col(f"LocusId").is_in(set_to_hom_ref)).then(pl.col(f"NumRepeatsInReference")).otherwise(pl.col(f"NumRepeatsLongAllele:{sample_id}")).alias(f"NumRepeatsLongAllele:{sample_id}"),
    )

    if bed_file_i % 100 == 0:
        temp_file = f"temp_df2.tsv.gz"
        with gzip.open(temp_file, "wb") as f:
            joined_variant_table.write_csv(f, separator="\t")
        print(f"Wrote {joined_variant_table.height:,d} loci to {temp_file}")

        joined_variant_table = pl.read_csv(temp_file, separator="\t", schema_overrides=schema_overrides)
        print(f"Read {joined_variant_table.height:,d} loci from {temp_file}")

# Write the joined variant table to a gzipped file
with gzip.open(args.output_tsv, "wb") as f:
    joined_variant_table.write_csv(f, separator="\t")

joined_variant_table = joined_variant_table.with_columns(
    *[pl.col(f"NumRepeatsShortAllele:{s}").fill_null("missing").alias(f"NumRepeatsShortAllele:{s}") for s in sample_ids],
    *[pl.col(f"NumRepeatsLongAllele:{s}").fill_null("missing").alias(f"NumRepeatsLongAllele:{s}") for s in sample_ids],
)

for sample_id in sample_ids:
    sample_bed_path = f"{sample_id}.with_hom_ref_filled_in.bed"
    subset_df = joined_variant_table.select(
        pl.col("Chrom").cast(pl.Utf8).alias("chrom"),
        (pl.col("Start1Based") - 1).cast(pl.Int32).alias("start"),
        pl.col("End1Based").cast(pl.Int32).alias("end"),
        (pl.col(f"NumRepeatsShortAllele:{sample_id}").cast(pl.String) + "/" + pl.col(f"NumRepeatsLongAllele:{sample_id}").cast(pl.String)).alias("name"),
        pl.lit(".").alias("score"),
        pl.lit(".").alias("strand"),
    )
    subset_df = subset_df.sort("chrom", "start", "end")

    subset_df.write_csv(sample_bed_path, separator="\t", include_header=False)
    print(f"Wrote {subset_df.height:,d} rows to {sample_bed_path}")