"""Takes the joined variant table generated by the join_per_sample_variant_tables.py script and fills in homozygous-reference genotypes for loci that have no genotype for a sample but fall inside that sample's dipcall confidence regions.

Inputs:
- joined variant table
- dipcall confidence region bed file for each sample in the joined variant table

Outputs:
- joined variant table where loci with a missing genotype for a sample are set to homozygous reference (repeat counts = NumRepeatsInReference) when the locus is inside that sample's dipcall confidence region; genotypes outside the confidence region are left missing
"""

import argparse
import collections
from intervaltree import IntervalTree, Interval
import os
import pandas as pd
import tqdm

parser = argparse.ArgumentParser(description="Fill in homozygous-reference genotypes for missing-genotype loci inside dipcall confidence regions")
parser.add_argument("--output-tsv", help="Output joined variant table as a gzipped tsv file")
parser.add_argument("joined_variant_table", help="Joined variant table")
parser.add_argument("dipcall_confidence_regions", nargs="+", help="Dipcall confidence region bed file for each sample in the joined variant table")

args = parser.parse_args()

if not os.path.exists(args.joined_variant_table):
    parser.error(f"Joined variant table file {args.joined_variant_table} does not exist")

if not args.output_tsv:
    args.output_tsv = args.joined_variant_table.replace(".tsv", ".with_hom_ref_filled_in.tsv")

# Read string-typed columns as strings (Chrom must stay Utf8 to handle X, Y, etc.); numeric columns are inferred.
dtype_overrides = {
    "Chrom": str,
    "Locus": str,
    "LocusId": str,
    "Motif": str,
    "CanonicalMotif": str,
}

joined_variant_table = pd.read_csv(args.joined_variant_table, sep="\t", dtype=dtype_overrides)

sample_ids = set()
for column in joined_variant_table.columns:
    if column.startswith("NumRepeatsShortAllele:") or column.startswith("NumRepeatsLongAllele:"):
        sample_ids.add(":".join(column.split(":")[1:]))

print(f"Found {len(sample_ids):,d} samples in {args.joined_variant_table}")

sample_ids_to_bed_file_paths = {}
for sample_id in sample_ids:
    # find the dipcall confidence region bed file for this sample
    matching_bed_file_path = None
    for bed_file_path in args.dipcall_confidence_regions:
        bed_filename = os.path.basename(bed_file_path)
        # require sample_id to be followed by "." (e.g. "HG002.dip.bed.gz") so a shorter id can't match a longer
        # one's file as a substring (e.g. "HG002" must not match "HG00254.dip.bed.gz")
        if bed_filename.startswith(f"{sample_id}."):
            if matching_bed_file_path is not None:
                parser.error(f"Multiple DipCall confidence region bed files found for sample {sample_id}: {matching_bed_file_path} and {bed_file_path}")

            matching_bed_file_path = bed_file_path

    if matching_bed_file_path is None:
        parser.error(f"No dipcall confidence region bed file found for sample {sample_id}")

    if not os.path.isfile(matching_bed_file_path):
        parser.error(f"Dipcall confidence region bed file {matching_bed_file_path} does not exist")

    sample_ids_to_bed_file_paths[sample_id] = matching_bed_file_path


for bed_file_i, (sample_id, bed_file_path) in tqdm.tqdm(enumerate(sample_ids_to_bed_file_paths.items()), total=len(sample_ids_to_bed_file_paths), unit=" samples"):
    print(f"Processing sample {sample_id} from {bed_file_path}")
    # read the first 3 columns of the bed file (chrom, start, end)
    dipcall_confidence_regions = pd.read_csv(bed_file_path, sep="\t", header=None, dtype=str).iloc[:, :3]
    dipcall_confidence_regions.columns = ["Chrom", "Start0Based", "End1Based"]
    dipcall_confidence_regions["Start0Based"] = dipcall_confidence_regions["Start0Based"].astype(int)
    dipcall_confidence_regions["End1Based"] = dipcall_confidence_regions["End1Based"].astype(int)

    EMPTY_INTERVAL_TREE = IntervalTree()
    confidence_region_interval_trees = collections.defaultdict(IntervalTree)
    total_bases = 0
    for row in dipcall_confidence_regions.itertuples(index=False):
        if "_" in row.Chrom:
            continue
        normalized_chrom = row.Chrom.replace("chr", "").upper()
        confidence_region_interval_trees[normalized_chrom].add(Interval(row.Start0Based, row.End1Based))
        total_bases += row.End1Based - row.Start0Based

    print(f"Total bases in {bed_file_path}: {total_bases:,d}")

    short_allele_column = f"NumRepeatsShortAllele:{sample_id}"
    long_allele_column = f"NumRepeatsLongAllele:{sample_id}"

    # for each locus whose short and long alleles are both missing, check if the locus is in the interval tree
    set_to_hom_ref = set()
    both_missing = joined_variant_table[short_allele_column].isna() & joined_variant_table[long_allele_column].isna()
    for row in joined_variant_table.loc[both_missing, ["Chrom", "Start1Based", "End1Based", "LocusId"]].itertuples(index=False):
        normalized_chrom = row.Chrom.replace("chr", "").upper()
        if confidence_region_interval_trees.get(normalized_chrom, EMPTY_INTERVAL_TREE).overlaps(row.Start1Based - 1, row.End1Based):
            set_to_hom_ref.add(row.LocusId)

    print(f"Resetting {len(set_to_hom_ref):,d} out of {len(joined_variant_table):,d} ({(len(set_to_hom_ref)/len(joined_variant_table)):.1%}) genotypes to homozygous reference for sample {sample_id}")

    set_to_hom_ref_mask = joined_variant_table["LocusId"].isin(set_to_hom_ref)
    joined_variant_table.loc[set_to_hom_ref_mask, short_allele_column] = joined_variant_table.loc[set_to_hom_ref_mask, "NumRepeatsInReference"]
    joined_variant_table.loc[set_to_hom_ref_mask, long_allele_column] = joined_variant_table.loc[set_to_hom_ref_mask, "NumRepeatsInReference"]

    if bed_file_i % 100 == 0:
        temp_file = "temp_df2.tsv.gz"
        joined_variant_table.to_csv(temp_file, sep="\t", index=False, compression="gzip")
        print(f"Wrote {len(joined_variant_table):,d} loci to {temp_file}")

        joined_variant_table = pd.read_csv(temp_file, sep="\t", dtype=dtype_overrides)
        print(f"Read {len(joined_variant_table):,d} loci from {temp_file}")

# Write the joined variant table to a gzipped file
joined_variant_table.to_csv(args.output_tsv, sep="\t", index=False, compression="gzip")
